#!/usr/bin/env python3
"""
Crunchbase Investor Count Scraper

Reads cities from a CSV file and generates a JavaScript file that,
when executed in the Chrome console on crunchbase.com, queries the
internal Crunchbase API for investor counts by city and investor type.

Usage:
    python3 crunchbase_scraper.py generate [--dry-run] [--limit N]
    python3 crunchbase_scraper.py update <results.json>

Commands:
    generate    Generate JS script for Chrome console
    update      Update CSV with results from JS output
"""

import argparse
import csv
import json
import sys
from pathlib import Path

# Source CSV config
SOURCE_CSV = Path(__file__).parent / "data" / "source.csv"
OUTPUT_JS = Path(__file__).parent / "output" / "crunchbase_query.generated.js"
OUTPUT_DIR = Path(__file__).parent / "output"
RESULTS_JSON = OUTPUT_DIR / "results.json"

# Row range (1-indexed row numbers from the original CSV)
ROW_START = 532
ROW_END = 797

# CSV column indices
COL_ROW_NUM = 0
COL_AGGLOMERATION = 1
COL_CITY = 2
COL_REGION = 3
COL_COUNTRY = 4
COL_ANGEL = 5


def load_cities(source_path: Path, limit: int | None = None) -> list[dict]:
    """Load target cities from source CSV."""
    cities = []
    with open(source_path, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        header = next(reader)  # skip header
        for row in reader:
            if not row or not row[COL_ROW_NUM].strip():
                continue
            try:
                row_num = int(row[COL_ROW_NUM])
            except ValueError:
                continue
            if ROW_START <= row_num <= ROW_END:
                cities.append({
                    "row": row_num,
                    "agglomeration": row[COL_AGGLOMERATION],
                    "city": row[COL_CITY],
                    "region": row[COL_REGION],
                    "country": row[COL_COUNTRY],
                })
        if limit:
            cities = cities[:limit]
    return cities


def generate_js(cities: list[dict], dry_run: bool = False) -> str:
    """Generate JavaScript for Chrome console execution on crunchbase.com."""
    cities_json = json.dumps(cities, ensure_ascii=False, indent=2)

    if dry_run:
        return f"""
// === CRUNCHBASE SCRAPER — DRY RUN ===
// Cities to query: {len(cities)}

const CITIES = {cities_json};

console.log("=== DRY RUN: {len(cities)} cities to query ===");
CITIES.forEach((c, i) => {{
    console.log(`${{i + 1}}. Row ${{c.row}}: ${{c.city}}, ${{c.region}}, ${{c.country}}`);
}});
console.log("\\nRun without --dry-run to generate the actual query script.");
"""

    return f"""
// =============================================================
// CRUNCHBASE INVESTOR COUNT SCRAPER
// Generated by crunchbase_scraper.py
//
// INSTRUCTIONS:
// 1. Open https://www.crunchbase.com in Chrome
// 2. Log in to your Crunchbase account
// 3. Open DevTools (Cmd+Option+J)
// 4. Paste this entire script into the Console
// 5. Wait for completion (~{len(cities) * 3} seconds)
// 6. Copy the JSON output and save to output/results.json
// =============================================================

(async function() {{
    "use strict";

    const CITIES = {cities_json};

    const INVESTOR_TYPE = "angel";
    const DELAY_MS = 2500;
    const results = [];
    let errors = 0;

    // --- Utility ---
    function sleep(ms) {{
        return new Promise(r => setTimeout(r, ms));
    }}

    function log(msg) {{
        console.log(`[Scraper] ${{msg}}`);
    }}

    // --- Crunchbase Internal API ---

    // Resolve city name to Crunchbase location UUID
    async function resolveLocation(city, region, country) {{
        // Try specific query first: "city, region, country"
        const queries = [
            `${{city}}, ${{country}}`,
            `${{city}}, ${{region}}, ${{country}}`,
            city
        ];

        for (const query of queries) {{
            try {{
                const resp = await fetch(
                    `/v4/data/autocompletes?query=${{encodeURIComponent(query)}}&collection_ids=location.cities&limit=5`,
                    {{ credentials: "include" }}
                );

                if (!resp.ok) {{
                    log(`  Autocomplete HTTP ${{resp.status}} for "${{query}}"`);
                    continue;
                }}

                const data = await resp.json();
                const entities = data.entities || [];

                if (entities.length === 0) continue;

                // Try to find best match by country
                const countryLower = country.toLowerCase();
                const cityLower = city.toLowerCase();

                // Prefer exact city+country match
                for (const e of entities) {{
                    const val = (e.identifier?.value || e.value || "").toLowerCase();
                    if (val.includes(cityLower) && val.includes(countryLower)) {{
                        return e.identifier || e;
                    }}
                }}

                // Fallback to first result
                return entities[0].identifier || entities[0];
            }} catch (err) {{
                log(`  Autocomplete error for "${{query}}": ${{err.message}}`);
            }}
        }}

        return null;
    }}

    // Search for investor count
    async function searchInvestorCount(locationIdentifier) {{
        const body = {{
            field_ids: ["identifier", "short_description"],
            order: [{{ field_id: "rank_principal_investor", sort: "asc" }}],
            query: [
                {{
                    type: "predicate",
                    field_id: "investor_type",
                    operator_id: "includes",
                    values: [INVESTOR_TYPE]
                }},
                {{
                    type: "predicate",
                    field_id: "location_identifiers",
                    operator_id: "includes",
                    values: [locationIdentifier.uuid || locationIdentifier]
                }}
            ],
            limit: 1
        }};

        const resp = await fetch("/v4/data/searches/principal.investors", {{
            method: "POST",
            headers: {{ "Content-Type": "application/json" }},
            credentials: "include",
            body: JSON.stringify(body)
        }});

        if (!resp.ok) {{
            throw new Error(`Search API HTTP ${{resp.status}}: ${{await resp.text()}}`);
        }}

        const data = await resp.json();
        return data.count ?? data.total_count ?? 0;
    }}

    // --- Main Loop ---
    log(`Starting: ${{CITIES.length}} cities to query`);
    log(`Investor type: ${{INVESTOR_TYPE}}`);
    log(`Delay between requests: ${{DELAY_MS}}ms`);
    log("---");

    for (let i = 0; i < CITIES.length; i++) {{
        const {{ row, city, region, country }} = CITIES[i];
        const progress = `[${{i + 1}}/${{CITIES.length}}]`;

        try {{
            log(`${{progress}} ${{city}}, ${{region}}, ${{country}}...`);

            const location = await resolveLocation(city, region, country);

            if (!location) {{
                log(`${{progress}} Location not found — setting 0`);
                results.push({{ row, city, region, country, count: 0, status: "not_found" }});
                errors++;
            }} else {{
                const count = await searchInvestorCount(location);
                log(`${{progress}} -> ${{count}} angel investors`);
                results.push({{ row, city, region, country, count, status: "ok" }});
            }}
        }} catch (err) {{
            log(`${{progress}} ERROR: ${{err.message}}`);
            results.push({{ row, city, region, country, count: -1, status: "error", error: err.message }});
            errors++;
        }}

        if (i < CITIES.length - 1) {{
            await sleep(DELAY_MS);
        }}
    }}

    // --- Output ---
    log("---");
    log(`Done! ${{results.length}} cities processed, ${{errors}} errors`);
    log("");
    log("=== COPY THE JSON BELOW ===");

    const output = JSON.stringify(results, null, 2);
    console.log(output);

    log("=== END OF JSON ===");
    log("");
    log("Save the JSON above to: output/results.json");
    log("Then run: python3 crunchbase_scraper.py update output/results.json");

    // Also try to copy to clipboard
    try {{
        await navigator.clipboard.writeText(output);
        log("(JSON also copied to clipboard!)");
    }} catch (e) {{
        log("(Could not copy to clipboard — please copy manually)");
    }}

    return results;
}})();
"""


def cmd_generate(args):
    """Generate JS script from source CSV."""
    if not SOURCE_CSV.exists():
        print(f"Error: Source CSV not found at {SOURCE_CSV}")
        print(f"Copy the source CSV to: {SOURCE_CSV}")
        sys.exit(1)

    cities = load_cities(SOURCE_CSV, limit=args.limit)
    if not cities:
        print("Error: No cities found in the specified row range.")
        sys.exit(1)

    js_code = generate_js(cities, dry_run=args.dry_run)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_JS.write_text(js_code, encoding="utf-8")

    print(f"Generated: {OUTPUT_JS}")
    print(f"Cities: {len(cities)}")

    if args.dry_run:
        print("(Dry run — script will only list cities, not query)")
    else:
        print()
        print("Next steps:")
        print("  1. Open https://www.crunchbase.com and log in")
        print("  2. Open Chrome DevTools Console (Cmd+Option+J)")
        print(f"  3. Paste contents of {OUTPUT_JS}")
        print("  4. Wait for completion")
        print(f"  5. Save JSON output to {RESULTS_JSON}")
        print(f"  6. Run: python3 crunchbase_scraper.py update {RESULTS_JSON}")


def cmd_update(args):
    """Update source CSV with results from JS output."""
    results_path = Path(args.results_file)
    if not results_path.exists():
        print(f"Error: Results file not found: {results_path}")
        sys.exit(1)

    with open(results_path, "r", encoding="utf-8") as f:
        results = json.load(f)

    # Build lookup: row_num -> count
    counts = {}
    for r in results:
        if r["status"] == "ok":
            counts[r["row"]] = r["count"]
        elif r["status"] == "not_found":
            counts[r["row"]] = 0

    # Read and update source CSV
    rows = []
    updated = 0
    with open(SOURCE_CSV, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        header = next(reader)
        rows.append(header)
        for row in reader:
            if row and row[COL_ROW_NUM].strip():
                try:
                    row_num = int(row[COL_ROW_NUM])
                    if row_num in counts:
                        row[COL_ANGEL] = str(counts[row_num])
                        updated += 1
                except ValueError:
                    pass
            rows.append(row)

    # Write updated CSV
    updated_csv = OUTPUT_DIR / "updated_source.csv"
    with open(updated_csv, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerows(rows)

    # Summary
    errors = [r for r in results if r["status"] == "error"]
    not_found = [r for r in results if r["status"] == "not_found"]

    print(f"Updated: {updated} rows")
    print(f"Not found: {len(not_found)} cities")
    print(f"Errors: {len(errors)} cities")
    print(f"Output: {updated_csv}")

    if errors:
        print("\nCities with errors:")
        for e in errors:
            print(f"  Row {e['row']}: {e['city']} — {e.get('error', 'unknown')}")

    if not_found:
        print(f"\nCities not found in Crunchbase ({len(not_found)}):")
        for nf in not_found[:10]:
            print(f"  Row {nf['row']}: {nf['city']}, {nf['region']}, {nf['country']}")
        if len(not_found) > 10:
            print(f"  ... and {len(not_found) - 10} more")


def main():
    parser = argparse.ArgumentParser(
        description="Crunchbase Investor Count Scraper"
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # generate
    gen_parser = subparsers.add_parser("generate", help="Generate JS query script")
    gen_parser.add_argument("--dry-run", action="store_true",
                            help="Generate script that only lists cities")
    gen_parser.add_argument("--limit", type=int, default=None,
                            help="Process only first N cities")

    # update
    upd_parser = subparsers.add_parser("update", help="Update CSV with results")
    upd_parser.add_argument("results_file", help="Path to results JSON file")

    args = parser.parse_args()

    if args.command == "generate":
        cmd_generate(args)
    elif args.command == "update":
        cmd_update(args)


if __name__ == "__main__":
    main()
